---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-combined-monorepo
  title: Sample combined monorepo
  description: A combined monorepo
  annotations:
    github.com/project-slug: RoadieHQ/sample-combined-monorepo
    backstage.io/techdocs-ref: dir:.
  tags: 
    - nodejs
spec:
  type: service
  owner: engineering
  lifecycle: experimental
