site_name: Root docs

nav:
  - Home: index.md
  - Subdirectory docs:
    - Calculator service: '!include ./services/calculator-service/mkdocs.yml'
    - Candle service: '!include ./services/candle-service/mkdocs.yml'

plugins:
  - monorepo
  - techdocs-core
